system_pkg: 0x17108fb344dbea0d315e6f44cdd3af12a028cd568bafcbfb7f7a7b152719d15d
system_object: 0x3fb18e675ad41158f59acbdb7f574136a198cbd83be9b968c0fdeaa139c312f9

# You can define a custom path to your Sui wallet configuration here. If this is unset or `null`,
# the wallet is configured from `./client.yaml`, `./sui_config.yaml` (both relative to your current
# working directory), or `~/.sui/sui_config/client.yaml` in this order.
wallet_config: null

# Default values for the client are commented out.
#
# There is no risk in playing around with these values.
# Worst case, you may not be able to store/read from Walrus.

# communication_config:
#   max_concurrent_writes: null
#   max_concurrent_sliver_reads: null
#   max_concurrent_metadata_reads: 3
#   reqwest_config:
#     total_timeout:
#       secs: 180
#       nanos: 0
#     pool_idle_timeout: null
#     http2_keep_alive_timeout:
#       secs: 5
#       nanos: 0
#     http2_keep_alive_interval:
#       secs: 30
#       nanos: 0
#     http2_keep_alive_while_idle: true
#   request_rate_config:
#     max_node_connections: 10
#     max_retries: 5
#     min_backoff:
#       secs: 2
#       nanos: 0
#     max_backoff:
#       secs: 60
#       nanos: 0
