// editorconfig-checker-disable-file
// Data here autogenerated by python file

// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

#[test_only]
module blob_store::committee_cert_tests {

    use sui::bls12381::{bls12381_min_pk_verify};

    use blob_store::bls_aggregate::new_bls_committee;
    use blob_store::committee::{Self, Committee, committee_for_testing_with_bls , verify_quorum_in_epoch};
    use blob_store::storage_node;

   #[test]
    public fun test_basic_correct() : Committee {

        let pub_key_bytes = vector[142, 78, 70, 3, 179, 142, 145, 75, 170, 36, 5, 232, 153, 164, 205, 57, 24, 216, 208, 34, 87, 213, 225, 76, 5, 157, 212, 88, 161, 34, 75, 145, 206, 144, 85, 11, 197, 110, 75, 175, 215, 194, 78, 51, 192, 196, 59, 204];
        let message = vector[1, 0, 3, 5, 0, 0, 0, 0, 0, 0, 0, 104, 101, 108, 108, 111];
        let signature = vector[173, 231, 27, 143, 41, 154, 49, 14, 85, 88, 187, 65, 86, 190, 161, 255, 219, 210, 78, 88, 179, 53, 11, 104, 168, 220, 40, 13, 91, 254, 191, 116, 161, 252, 196, 19, 24, 153, 126, 248, 68, 136, 245, 85, 144, 17, 163, 161, 10, 195, 145, 26, 88, 205, 255, 211, 19, 42, 132, 34, 230, 155, 148, 10, 173, 151, 182, 93, 50, 73, 126, 112, 119, 153, 116, 80, 198, 215, 82, 228, 9, 186, 90, 83, 85, 143, 155, 191, 109, 190, 84, 129, 178, 100, 228, 118];

        assert!(bls12381_min_pk_verify(
            &signature,
            &pub_key_bytes,
            &message), 0);

        // Make a new committee
        let bls_committee = new_bls_committee(
            vector[
                storage_node::new_for_testing(pub_key_bytes, 10)
            ]
        );

        // actual committee

        let committee_at_5 : Committee = committee_for_testing_with_bls(5, bls_committee);
        let cert = verify_quorum_in_epoch(&committee_at_5, signature, vector[0], message);

        assert!(committee::intent_type(&cert) == 1, 0);

        committee_at_5
    }

    #[test, expected_failure]
    public fun test_incorrect_epoch() : Committee {

        let pub_key_bytes = vector[142, 78, 70, 3, 179, 142, 145, 75, 170, 36, 5, 232, 153, 164, 205, 57, 24, 216, 208, 34, 87, 213, 225, 76, 5, 157, 212, 88, 161, 34, 75, 145, 206, 144, 85, 11, 197, 110, 75, 175, 215, 194, 78, 51, 192, 196, 59, 204];
        let message = vector[1, 0, 3, 5, 0, 0, 0, 0, 0, 0, 0, 104, 101, 108, 108, 111];
        let signature = vector[173, 231, 27, 143, 41, 154, 49, 14, 85, 88, 187, 65, 86, 190, 161, 255, 219, 210, 78, 88, 179, 53, 11, 104, 168, 220, 40, 13, 91, 254, 191, 116, 161, 252, 196, 19, 24, 153, 126, 248, 68, 136, 245, 85, 144, 17, 163, 161, 10, 195, 145, 26, 88, 205, 255, 211, 19, 42, 132, 34, 230, 155, 148, 10, 173, 151, 182, 93, 50, 73, 126, 112, 119, 153, 116, 80, 198, 215, 82, 228, 9, 186, 90, 83, 85, 143, 155, 191, 109, 190, 84, 129, 178, 100, 228, 118];

        assert!(bls12381_min_pk_verify(
            &signature,
            &pub_key_bytes,
            &message), 0);

        // Make a new committee
        let bls_committee = new_bls_committee(
            vector[
                storage_node::new_for_testing(pub_key_bytes, 10),
            ]
        );

        // actual committee

        // INCORRECT EPOCH
        let committee_at_6 : Committee = committee_for_testing_with_bls(6, bls_committee);
        let cert = verify_quorum_in_epoch(&committee_at_6, signature, vector[0], message);

        assert!(committee::intent_type(&cert) == 1, 0);

        committee_at_6
    }

}
