# See https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#markdownlint-cli2jsonc
# for configuration options and https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# for available rules.
globs:
  - "**/*.md"
gitignore: true
config:
  default: true
  line-length:
    line_length: 100
    heading_line_length: 80
    code_block_line_length: 150
    tables: false
    stern: true
  heading-style:
    style: atx
  ul-style:
    style: dash
  ol-prefix:
    style: one
  emphasis-style:
    style: asterisk
  bold-style:
    style: asterisk
  proper-names:
    code_blocks: false
    html_elements: false
    names:
      - Byzantine
      - dApp
      - GitHub
      - internet
      - JavaScript
      - Mainnet
      - Merkle
      - Mysten Labs
      - Python
      - Rust
      - Sui
      - SUI
      - SuiNS
      - Testnet
      - testnets
      - Walrus
      - Walrus Site
      - Walrus Sites
      - web
      - web2
      - web3
