name: Other Issue
description: Report any other potential improvement.
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to improve Walrus!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue.
      placeholder: "The CI should also test ..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/MystenLabs/walrus-sites/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
